# -*- coding: utf-8 -*-
"""web scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dtl0MTP0mJ5zS9DjSgslx4EbzzqguQU
"""

import requests
import bs4
import csv

data = requests.get('https://www.checkraka.com/house/?quicksearch_order=ASC&page=')
data

soup = bs4.BeautifulSoup(data.text)

soup

all_house = soup.find_all('div',{'class' : 'product-highlight-item category-44' })

for house in all_house:
  print(house.find('div',{'class': 'mid'}).text.strip());
  print(house.find('div',{'class': 'card'}).text);
  print()

with open('houses.csv', mode='w', newline='', encoding='utf-8-sig') as file:
    writer = csv.writer(file)

    # เขียน header ของตาราง
    writer.writerow(['Name', 'Price'])

    page = 1  # เริ่มจากหน้าที่ 1

    while page <= 50:  # วนลูปสูงสุด 50 หน้า
        url = f'https://www.checkraka.com/house/?quicksearch_order=ASC&page={page}'
        print(f"Fetching data from page {page}...")

        # ดึงข้อมูลจากเว็บเพจ
        data = requests.get(url)
        soup = bs4.BeautifulSoup(data.text, 'html.parser')

        # หาทุก div ที่มี class ชื่อ 'product-highlight-item category-44'
        all_house = soup.find_all('div', {'class': 'product-highlight-item category-44'})

        # ถ้าไม่พบข้อมูลในหน้านี้ แสดงว่าไม่มีหน้าถัดไปแล้ว
        if not all_house:
            print("No more data found.")
            break

        # วนลูปดึงข้อมูลและเขียนลงในไฟล์ CSV
        for house in all_house:
            name = house.find('div', {'class': 'mid'}).text.strip()
            details = house.find('div', {'class': 'card'}).text.strip().split('\n')

            # แยก Project Name และ Price ออกจากกัน
            project_name = details[0].strip()
            price = details[1].strip() if len(details) > 1 else ''

            # รวม Name และ Project Name เข้าด้วยกัน
            full_name = f"{name}\n{project_name}"

            # เขียนข้อมูลในแต่ละแถวลงในไฟล์ CSV
            writer.writerow([full_name, price])

        # เพิ่มหมายเลขหน้าสำหรับหน้าถัดไป
        page += 1

print("Data has been exported to houses.csv")